- name: install MariaDB on Ubuntu
  apt:
    name: mariadb-server
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install MariaDB on CentOS
  dnf:
    name: mariadb-server
    state: present
  when: ansible_distribution == "CentOS"

- name: ensure MariaDB is running
  service:
    name: mariadb
    state: started
    enabled: true
